### ISSUE TITLE
แก้ไขเพิ่ม#01 by.KIM

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#14]
- แก้ปั้มให้ปล้นได้เฉพาะปั้มที่อยู่ถนนเส้นส้มเพราะ ตำรวจไปไม่ถึงปั้มที่เป็นชนบท และป้องกันการปั้มเงินในการปล้นปั้มแบบเดินสายปล้น
- แก้ ฮอ หมอที่บัค ซื้อแล้วระเบิด 2 ลำสุดท้าย
- แก้รถ ฮันเตอร์ตำรวจ ยศ 3 บั้งขึ้นไปถึงจะซื้อได้เท่านั้น
- แก้ราคาตอนประกันตัวออกจากคุกที่มี โต๊ะในคุกตอนี้จ่ายแค่ 1500 ได้ออกจากคุกแต่แก้ให้จ่าย 150000 ออกจากคุกได้
ได้เลยโดยไม่ต้องเสียตังสักบาท
- แก้ทำให้ตำรวจยศ 1 เกิด สน. AIR HQ ได้ [ ปกติยศ 1 เกิดไม่ได้ ] และ ยศ 1 ใช้ฟังชั่น ลบ ปืนไม่ได้
- แก้ทำให้ส่งเข้าคุกใส่เวลาได้
- เพิ่มจุดบนแมพในส่วนของ Supercar ปกติตอนนี้ไม่มีโชวบนแมพ

**** เพิ่มเติม ****
- แก้ไขจุดสปาว ฮอ ที่ อเทล่า... เนื่องจาก พอกดสปาวแล้ว ไปเกิดอยู่ใต้น้ำมุมล่างซ้ายของแมพ
- แก้ไข คีย์รถยานพาหนะ เวลาออกเกมส์เข้าใหม่แล้วคีย์มันหาย... ต้อง อิมพาว เท่านั้น
- แก้ไขในการโชวของ หกเหลี่ยม ในทีมเดียวกันแก๊งเดียวกันเนื่องจากมีผู้เล่น ร้องขอเป็นจำนวน 7 คนโดยประมาน

**Comment by EagleonePrimo** [comment]
คราวหน้าแยกเป็น ข้อๆไปเลยก็ดีนะ โพสละข้อ

**Comment by EagleonePrimo** [comment]
เอาพวกนี้แต่ละขอไปแยกเป็นหัวข้อย่อยๆเลยนะ 1 หัวข้อ ต่อ 1 โพส

**Comment by EagleonePrimo** [comment]
เอาไปแยกซะนะ
