### ISSUE TITLE
รถบัคใน Car Shop #07 by.KIM

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#21]
บัคแบบซื้อมาแล้วปลดล๊อครถไม่ได้

cl3_xr_1000_Blk
cl3_xr_1000_Yel
cl3_xr_1000_Blu
cl3_xr_1000_Red
cl3_xr_1000_Green
cl3_xr_1000_Org

**Comment by EagleonePrimo** [comment]
แก้ใขแล้ว
