### ISSUE TITLE
แก้ใขราคาของในเซิฟทุกชนิด

### ISSUE THREAD

**Issue by EagleonePrimo** [EGEStudio/Victory-LifeProject#33]
อ้างอิงตามราคาบนชีวิตจริง

**Comment by EagleonePrimo** [comment]
M320
$11,700.00–$13,760.00
405 447.552 - 476 834.044 Thai baht

[อ้างอิง](http://www.cheytac.com/shop/firearms/m200-intervention/)

**Comment by EagleonePrimo** [comment]
GM6
$14,999.00
519 769.9 Thai baht

[อ้างอิง](http://www.tacticalimports.ca/gm6-lynx-p-3.html)

**Comment by EagleonePrimo** [comment]
RPK
$1000 - $1200
34 653.6369 - 41 584.3643 Thai baht

[อ้างอิง](http://www.gunwatcher.com/Search/rpk-for-sale)

**Comment by EagleonePrimo** [comment]
#43

**Comment by EagleonePrimo** [comment]
#45

**Comment by gameskim01** [comment]
แก้ราคาใบเรเบลเหลือ 150000

**Comment by EagleonePrimo** [comment]
250000 ขาดตัว

**Comment by EagleonePrimo** [comment]
ไปแจ้งต่อที่ #45 เปิด Pull แล้ว
