### ISSUE TITLE
รูป สัญลักษ์ของ ประธานาธิปดี

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#35]
https://www.google.co.th/search?q=president&biw=1282&bih=766&source=lnms&tbm=isch&sa=X&sqi=2&ved=0ahUKEwjt59Gy97HPAhXHso8KHcrgBV4Q_AUIBigB#tbm=isch&q=president+logo&imgrc=9giV_kBN8ZHTKM%3A

**Comment by EagleonePrimo** [comment]
เข้ามีของเขาอยู่แล้ว
