### ISSUE TITLE
เปิดใช้งาน ระบบ บั้งหกเหลี่ยม แก๊งของตัวเองให้เป็นปกติ

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#42]
เปิดใช้งาน ระบบ บั้งหกเหลี่ยม แก๊งของตัวเองให้เป็นปกติ

**Comment by gameskim01** [comment]
อาการคือ เวลาอยู่ห่างจะไม่เห็นบั้งแก๊งเพื่อนของตัวเอง

**Comment by EagleonePrimo** [comment]
ยอมก็ได้

**Comment by EagleonePrimo** [comment]
ใช้งานได้ 20.00 น. 3/10/2559
