### ISSUE TITLE
ระบบ เคอร์ฟิล

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#50]
ระบบ เคอร์ฟิล ที่ Rank 4 ขึ้นไปสามารถทำได้
รูปแบบที่ออกมาอาจจะเป็นการพิมพ์ ประกาศผ่านข้อความแบบให้ทุกคน All player หัวข้อประกาศ เปลื่ยนเป็น จากกรมตำรวจ อะไรทำนองนี้

**Comment by gameskim01** [comment]
ทุกวันนี้โจรเยอะมาก ตำรวจคุมสถานการณ์ได้ยาก ทดสอบข้อเท็จจริงโดย Admin KIM เพราะผลออกมาแบบนีเลยจะให้ ลง อาวุธ ยานพาหนะ ให้ทางกรมตำรวจ ได้ใช้กันอย่างสะดวกมากขึ้น เพราะเหตุการณ์ทุกวันนี้ กรมตำรวจเสียเปรียบอย่างมากและเห็นได้ชัด เช่น จำนวนตำรวจ และ อาวุธ

**Comment by EagleonePrimo** [comment]
#86
