### ISSUE TITLE
ปลดแบนผู้ที่ไม่เกี่ยวกับเหตุการ การใช้โปรแกรมเมื่อวันที่ 6/10/2559

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#53]
ชื่อ Bangron เนื่องจากมีการเติมเงินเข้าระบบเมื่อวานนี้เลยคิดว่าไม่น่าจะป็นผู้ใช้โปรแกรมช่วยเล่น
ชื่อ Skaled เป็นผู้เล่นธรรมดาที่ถูกดึงเข้าแก๊งในวันที่เกิดเหตุการณ์แต่ ADMIN KIM รับรองได้เพราะว่าเคยเล่นด้วยกันมาก่อนและภายหลังจากเกิดเหตุการณ์ Skaled ได้เป็นสายอยู่ในแก๊งนั้นได้ให้ข้อมูลกับผม และนี่คือเหตุผลที่เชื่อว่า ทั้ง 2 คนนี้ไม่ใช่ผู้ที่ใช้โปรแกรมช่วยเล่นครับ

**Comment by EagleonePrimo** [comment]
ปลดหมดแล้ว

**Comment by gameskim01** [comment]
ปลดแบนเพิ่มเติม
FDTheJoke เนืองจากผู้เล่นให้การว่า เค้าไม่รู้จักกับแก๊งนี้มาก่อนแต่ แต่สาเหตุที่อยู่ในแก๊งเพราะตนไม่มีแก๊งอยู่และพึ่งได้เข้าแก๊งนี้ไปเมื่อวันที่เกิดเหตุครับ
