### ISSUE TITLE
ปัญหา MISSION FAILED จำนวนหลายคน

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#54]
มีผู้เล่นจำนวนมากที่เกิดปัญหา MISSION FAILED เข้าเกมส์กันไม่ได้ขอวิธีแก้ด้วยครับ

**Comment by EagleonePrimo** [comment]
เช็ค Mod เปิน Anti Hack ชั้น 2 แล้ว

**Comment by EagleonePrimo** [comment]
ea64d4dd77baa22d01ca62d056f422ae78e59f67
