### ISSUE TITLE
แจ้งบัควันที่ 9/10/2559 ของเวอร์ชั่น 1.64

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#61]
1.- เข้าเกมส์ แล้วออกเข้าใหม่ ของหาย เช่น หมวก ชุด ปืน เกราะ ไนท์วิชชั่น หายทุกอย่าง ใบไลเซ้นก็หายหมดยกชุด ของในตัวหายหมดทุกอย่าง TEST  แล้ว โดย ADMIN KIM
2.- จุดหกเหลี่ยมกลับมาไม่เหมือนเดิมคือออกห่างแล้วบั้งหกเหลี่ยมหายไปเหมือนในตอนแรกของเวอร์ชั่น 1.62
3.- แก้อาการหมอกหนาเกินไป
4.- Wanted ตำรวจบัคไม่ขึ้นชื่อผู้กระทำผิดไม่ขึ้นในตัว Y

**Comment by EagleonePrimo** [comment]
ข้อ 4 ซ่ำ #19 
ข้อ 3 ตั้งใหม่ #65
ข้อ 2 แก้แล้ว
ข้อ 1 #63  #46
