### ISSUE TITLE
ปลดแบน ZERway

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#62]
เนื่องจากเจ้าตัวมารายงานตัวว่าไม่ได้มีการใช้โปรแต่อย่างใดสาเหตุที่ ฮอ ตกแล้วไม่ตายเนื่องจาก ฮอ จอดฉุกเฉินได้ทันเวลา และ เลือดลดแต่ไม่ถึงกับตาย และผู้แจ้งแบนมีเพียงคำให้การเท่านั้นไม่มีหลักฐานแต่อย่าง การแบนครั้งนี้เพื่อให้ ZERway มารายงานตัวเท่านั้น

**Comment by EagleonePrimo** [comment]
ปลดแล้ว
