### ISSUE TITLE
ด่วน !! แจ้งบัควันที่ 10/10/2559 ของเวอร์ชั่น 1.64

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#63]
1.- เข้าเกมส์ แล้วออกเข้าใหม่ ของหาย เช่น หมวก ชุด ปืน เกราะ ไนท์วิชชั่น หายทุกอย่าง ใบไลเซ้นก็หายหมดยกชุด ของในตัวหายหมดทุกอย่าง TEST แล้ว โดย ADMIN KIM

**Comment by EagleonePrimo** [comment]
แก้ใขแล้วใน #46
