### ISSUE TITLE
แจ้งบัคตำรวจ 11/10/2559

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#64]
ขอแจ้งเรื่องบักของ Arma 3 VICTORY APEX 1.64 ทางตำรวจที่พบเมื่อวันที่11/10/2559

รายละเอียดมีดังนี้

ตำรวจได้ทำการล๊อกตัวของซิวิเลียนแล้ว  หลังจากใช้คำสั่งที่ชื่อว่า ESCORT-PLAYERกับผู้เล่น

เพื่อจับลากแล้ว จะไม่สามารถกดปุ่ม windows เพื่อทำการอย่างอื่นได้เลย  ทำให้เกิดการบักขึ้น ต้องให้เพื่อนกดได้แต่ UN-RESTRAIN เท่านั้น ปล่อยตัว

แล้วถ้าสามารถนำขึ้นรถได้จะทำให้ซิวิเลียนที่โดนจับ  เมื่อผ่านไปสักพักทำให้ซิวิเลียนท่านนั้นเกิด disconet ได้ คือหลุดออกจากเกมส์ถานเดียว(โดยที่ไม่ตั้งใจ)

จึงขอแจ้งอาการและสาเหตุที่พบไว้ ณ เบื่อต้น

**Comment by EagleonePrimo** [comment]
แก้แล้ว 2684a75fefab516d2571f7802daad75f1535eb22
