### ISSUE TITLE
รายงานการขอ ปืนรีเบล เพิ่ม และข้อมูลอ้างอิงพร้อม

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#68]
รายชื่อปืนเรเบลที่อยากให้เอาเข้า
หมวดปืน
1. Type-115    2. MAR-10     3. MP7 HOLO    4. SPAR-17      5. CAR-95    6. CAR-95
7.  Protector    8. AK-12     9. M14 DMR     10. G3A3 เพิ่มกระสุน    11. RRA LAR-15
12. ASP        13. MKI-EMR     14. BCM      15. Suppressor 5.56 , 6.5 , 7.62     
16. HK-PSG1  17.  NVS Scrop
หมวดชุด
1. Light Combat Helmet          2. Heli Crew Helmet  3. Enhanced Combat Helmet    
4. Special  Purpose Helmet      5. Crew Helmet    6. Pilot Coveralls
หมวดเฮลิคอปเตอร์
1. MI-290 Taru
2. HellCat
3. Mo-hawk
4. B-206BLS

เหตุผลเพราะ เซิฟตอนนี้เริ่มนิ่งเพราะว่าไม่ค่อยจะมีอะไรมาใหม่เลยอยากให้เอาปืน รถ ชุดเข้ามาในเซิฟให้เซิฟนั้นมีอะไรใหม่บ้างๆและรับมือกับ NATO และเพิ่มประสิทธิภาพของ Rebel
ขอให้พิจารณาปืนมา ณ ที่นี้ด้วยครับ

**Comment by EagleonePrimo** [comment]
ขอรายชื้อคนที่ขอหน่อย

**Comment by EagleonePrimo** [comment]
ขอรายชื่อคนขอ ด่วน

**Comment by gameskim01** [comment]
รายชื่อคนอยากได้ปืน
1.AlphaWolf               2.64BITzB                3.VICTORIA  CRIMSON
4.Jame me na              5.Polis                       6.Skaled
7.PoomPaee                8.SOUL                     9.Tempesta
10.Kwan                     11.Korwizh               12.Razer  XD
13.CooPer                   14.Koonter                15.Xalway
16.Mr.Calos                 17.Mihawk               18.Kowtch

**Comment by gameskim01** [comment]
![default](https://cloud.githubusercontent.com/assets/21985101/19408909/6511222c-92f2-11e6-86c0-79281850fb3d.jpg)

**Comment by gameskim01** [comment]
![default](https://cloud.githubusercontent.com/assets/21985101/19408943/011b7c80-92f3-11e6-9ee4-bf6f353cd8f0.jpg)

**Comment by gameskim01** [comment]
![default](https://cloud.githubusercontent.com/assets/21985101/19408948/2334588c-92f3-11e6-8ab7-7370cb22519f.jpg)

**Comment by gameskim01** [comment]
![default](https://cloud.githubusercontent.com/assets/21985101/19408957/4faf9020-92f3-11e6-93fc-83a972477c73.jpg)
