### ISSUE TITLE
เพิ่มราคาการทำงานต่างๆ

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#70]
เนื่องจากมี CIV จำนวนหลายคนให้คำแนะนำ และ ร้องขอ ให้เพิ่มกำไลจากการทำงาน ให้เยอะกว่าเดิมขึ้นมา อาจจะไม่ต้องถึงเยอะมาก แต่อยากให้เยอะกว่านี้ขยับขึ้นไปอีกระดับนึง เพราะสังคมทุกวันนี้มีคนทำงาน แค่วันเดียวแล้วก็เลิกเล่นไปเป็นจำนวนมากเนื่องจากมีปัญหาเหล่านี้
1.เอายานพาหนะที่เอาครั้งที่เอาออกต้องเสียเงินเป็นจำนวนเยอะ [ ข้อนี้อาจจะไม่ต้องแก้อะไรหากเพิ่มฐานกำไลอาชีพแต่ละอาชีพ ] เช่น รถ Box NATO เอาออก 75000 
2.รถบรรทุกได้น้อย [ ข้อนี้อาจจะแก้ตรงให้บรรทุก ทุกคันเพิ่มมาสัก 100 หรือ 200 ]
3.ทุกครั้งที่ทำงานมีความเสี่ยงโดนฆ่า และ ไม่คุ้มเวลา [ ข้อนี้เป็นเรื่องของจิตใจแต่เราอาจจะแก้ได้หากเราเพิ่มฐานเงินกำไลจากอาชีพให้มีคนสนใจการทำงานมากขึ้น ]

ปัญหาทุกอย่างผมคิดว่าแก้ได้หากเพิ่มฐานเงินกำไล ให้มากกว่าเดิม

**Comment by EagleonePrimo** [comment]
#43  มีโปรเจคอยู่แล้ว

**Comment by EagleonePrimo** [comment]
เอารายชื้อคนมาด้วยไม่งั้นถือว่าพูดปากเปล่า

**Comment by gameskim01** [comment]
![default](https://cloud.githubusercontent.com/assets/21985101/19451084/2952ff2c-94d6-11e6-9757-7b2b524bcaf8.jpg)

**Comment by EagleonePrimo** [comment]
#43  #45
