### ISSUE TITLE
รายการของที่อยากให้เพิ่มมูลค่าผลกำไลจากการทำงานโดยกลุ่มผู้เล่น

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#72]
รายการของที่อยากให้เพิ่มมูลค่า
1.เพชร
2.เฮโรอีน
3.โคเคน
4.เต่า
สาเหตุ เพราะ ผู้เล่นใหม่บางท่านต้องการหาตังแต่หาตังได้ยากมากเพราะของราคาแต่ล่ะอย่างมันถูกยกตัวอย่างเช่น 
1.เพชร มูลค่า 1000 บาท
2.เต่า  มูลค่า  3600 บาท 
3.โคเคน  มูลค่า  1300 บาท(โดยประมาณ)
4.เฮโรอีน  มูลค่า  3100 บาท
อยากให้เพิ่มมากกว่าเดิมคือ
1.เพชร มูลค่า จาก 1000 บาท เป็น 5500 บาท
2.เต่า  มูลค่า  จาก  3600 บาท เป็น 13000 บาท
3.โคเคน  มูลค่า  จาก  1300 บาท  เป็น  7500 บาท
4.เฮโรอีน  มูลค่า  จาก  3100 บาท เป็น  7000 บาท
![default](https://cloud.githubusercontent.com/assets/21985101/19364390/38b0af6c-91b8-11e6-8973-fbfa75584a98.jpg)
รายงานนี้ผู้ทำคือ กลุ่มแก๊ง SIMIPRO ทั้งหมด
1.AlphaWolf               2.64BITzB                3.VICTORIA  CRIMSON
4.Jame me na              5.Polis                       6.Skaled
7.PoomPaee                8.SOUL                     9.Tempesta
10.Kwan                     11.Korwizh               12.Razer  XD
13.CooPer                   14.Koonter                15.Xalway
16.Mr.Calos                 17.Mihawk               18.Kowtch

**Comment by EagleonePrimo** [comment]
#43
