### ISSUE TITLE
เช็คตรวจสอบ/ปลดแบน

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#76]
GreeNDiamond :: เค้าบอกว่าโดนแบนแบบ งงๆ
MezX อันนี้ขึ้นแบนในรูปเปนของ MezX 
![14647380_170467410074111_1740342550_o](https://cloud.githubusercontent.com/assets/21985101/19394848/1893277a-9265-11e6-8090-51e2931c769e.jpg)
BeagleNiner :: เค้าบอกว่าโดนปลดแล้ว แต่ก็โดนแบนอีกครั้ง

**Comment by EagleonePrimo** [comment]
Hack แน่นอน

**Comment by gameskim01** [comment]
แล้ว BeagleNine ปลดยังครับ รอเล่น 3 วันได้แล้ว

**Comment by EagleonePrimo** [comment]
กลุ่มคนป่วนเซิฟ ไม่ใช่หลอ?
