### ISSUE TITLE
ดิสออก เข้ามาคีย์บ้านหาย

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#82]
![default](https://cloud.githubusercontent.com/assets/21985101/19474560/52b627b6-955a-11e6-86f9-bbb6d50b475a.jpg)

**Comment by EagleonePrimo** [comment]
ผมลองแล้วไม่หายนะ

**Comment by EagleonePrimo** [comment]
ปิด
