### ISSUE TITLE
แจ้งบัคเงินของตำรวจ

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#87]
![1](https://cloud.githubusercontent.com/assets/21985101/19509934/48d11d12-960b-11e6-907f-75a1ec7fef1f.jpg)
เนื่องจากการบัคนี้ วิธีทำคือการกดยัดข้อหาให้ผู้เล่นในจำนวนเยอะๆๆๆ แล้วจับผู้เล่นส่งเข้าคุก แล้วตำรวจนายนั้นจะได้ โบนัสเงินหมายจับจากระบบ

**Comment by EagleonePrimo** [comment]
จะแก้ในระบบ NATO #85
