### ISSUE TITLE
ตรวจเช็ค / ปลดแบน

### ISSUE THREAD

**Issue by gameskim01** [EGEStudio/Victory-LifeProject#88]
UID :: 76561200529093263
เนื่องจากโดนแบนจาก GNS เนื่องจากเข้าเกมส์แบบไม่ต้องล๊อคอิน แล้วกดเงินที่ ATM ได้ไม่จำกัดแบบ งงๆ

**Comment by EagleonePrimo** [comment]
ปลดแล้ว
